import CryptoKit
import Foundation

/// A TLS 1.3 byte transport authenticated with XTLS REALITY.
///
/// The ClientHello is generated by `TLS13Fingerprint`; the record and key
/// schedule live in `TLS13`.  Keeping this orchestration separate makes it
/// harder for ordinary Network.framework TLS to accidentally inherit
/// REALITY's intentionally non-X.509 certificate verification rules.
final class RealityTLSByteTransport: VisionDirectByteTransport {
    struct Configuration {
        let serverName: String
        let publicKey: Data
        let shortID: Data
        let alpn: [String]

        init(policy: ProxyPolicy, fallbackServerName: String) throws {
            serverName = policy.parameters["sni"]
                ?? policy.parameters["servername"] ?? fallbackServerName
            guard !serverName.isEmpty else {
                throw NativeOutboundError.protocolError("REALITY 缺少 server-name/SNI")
            }
            guard let encoded = policy.parameters["reality-public-key"]
                    ?? policy.parameters["public-key"],
                  let key = Self.decodeBase64URL(encoded), key.count == 32 else {
                throw NativeOutboundError.protocolError("REALITY public-key 必须是 32 字节 Base64URL X25519 公钥")
            }
            publicKey = key
            let rawShortID = policy.parameters["reality-short-id"]
                ?? policy.parameters["short-id"] ?? ""
            guard let id = Self.decodeHex(rawShortID), id.count <= 8 else {
                throw NativeOutboundError.protocolError("REALITY short-id 必须是最多 16 个十六进制字符")
            }
            shortID = id
            let configured = (policy.parameters["alpn"] ?? "")
                .split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
                .filter { !$0.isEmpty }
            alpn = configured.isEmpty ? ["h2", "http/1.1"] : configured
        }

        private static func decodeBase64URL(_ value: String) -> Data? {
            var normalized = value.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "-", with: "+")
                .replacingOccurrences(of: "_", with: "/")
            let remainder = normalized.count % 4
            if remainder != 0 { normalized += String(repeating: "=", count: 4 - remainder) }
            return Data(base64Encoded: normalized)
        }

        private static func decodeHex(_ value: String) -> Data? {
            let text = value.trimmingCharacters(in: .whitespacesAndNewlines)
            guard text.count % 2 == 0 else { return nil }
            var result = Data(); result.reserveCapacity(text.count / 2)
            var index = text.startIndex
            while index < text.endIndex {
                let next = text.index(index, offsetBy: 2)
                guard let byte = UInt8(text[index..<next], radix: 16) else { return nil }
                result.append(byte); index = next
            }
            return result
        }
    }

    private enum Phase { case handshaking, ready, closed }
    private let raw: any ByteTransport
    private let configuration: Configuration
    private let queue: DispatchQueue
    private let queueKey = DispatchSpecificKey<UInt8>()
    private var phase: Phase = .handshaking
    private var recordReader = TLS13.RecordReader()
    private var handshakeReader = TLS13.HandshakeReader()
    private var transcript: TLS13.Transcript?
    private var helloTranscriptHash = Data()
    private var schedule: TLS13.KeySchedule?
    private var serverHandshakeProtector: TLS13.RecordProtector?
    private var clientApplicationProtector: TLS13.RecordProtector?
    private var serverApplicationProtector: TLS13.RecordProtector?
    private var clientApplicationSecret: Data?
    private var serverApplicationSecret: Data?
    private var material: TLS13.ClientHelloMaterial?
    private var sessionID = Data()
    private var authKey = Data()
    private var leaf: TLS13.LeafCertificate?
    private var handshakeCompletion: ((Result<any ByteTransport, Error>) -> Void)?
    private var receiveCompletion: ((Data?, Bool, Error?) -> Void)?
    private var plaintextQueue: [Data] = []
    private var plaintextHead = 0
    private var receivingRaw = false
    private var sending = false
    private var sendQueue: [(Data, (Error?) -> Void)] = []
    private var visionDirectWrite = false
    private var visionDirectRead = false
    private var directReadBuffer = Data()

    static func upgrade(raw: any ByteTransport, policy: ProxyPolicy,
                        fallbackServerName: String, queue: DispatchQueue,
                        completion: @escaping (Result<any ByteTransport, Error>) -> Void) {
        do {
            let configuration = try Configuration(policy: policy,
                                                  fallbackServerName: fallbackServerName)
            let transport = RealityTLSByteTransport(raw: raw, configuration: configuration,
                                                     queue: queue)
            transport.handshakeCompletion = completion
            transport.startHandshake()
        } catch {
            raw.cancel(); completion(.failure(error))
        }
    }

    private init(raw: any ByteTransport, configuration: Configuration, queue: DispatchQueue) {
        self.raw = raw
        self.configuration = configuration
        self.queue = DispatchQueue(label: "app.hajimi.reality-tls", target: queue)
        self.queue.setSpecific(key: queueKey, value: 1)
    }

    private func startHandshake() {
        queue.async {
            do {
                let ephemeral = Curve25519.KeyAgreement.PrivateKey()
                let random = secureRandom(count: 32)
                var clearSession = Data(repeating: 0, count: 16)
                // Xray's four-byte client version tuple. Servers without an
                // explicit min/max accept any value; a contemporary non-zero
                // value also avoids looking like the legacy empty tuple.
                clearSession.replaceSubrange(0..<4, with: [1, 8, 0, 0])
                let seconds = UInt32(Date().timeIntervalSince1970)
                clearSession.replaceSubrange(4..<8, with: [
                    UInt8(truncatingIfNeeded: seconds >> 24),
                    UInt8(truncatingIfNeeded: seconds >> 16),
                    UInt8(truncatingIfNeeded: seconds >> 8),
                    UInt8(truncatingIfNeeded: seconds)])
                clearSession.replaceSubrange(8..<(8 + self.configuration.shortID.count),
                                             with: self.configuration.shortID)

                let shared = try TLS13.x25519(privateKey: ephemeral,
                                              peerPublicKey: self.configuration.publicKey)
                let extracted = TLS13.HKDF.extract(.sha256,
                                                   salt: Data(random.prefix(20)),
                                                   inputKeyMaterial: shared)
                self.authKey = try TLS13.HKDF.expand(.sha256,
                                                     pseudoRandomKey: extracted,
                                                     info: Data("REALITY".utf8), count: 32)
                let inputs = TLS13Fingerprint.ChromeClientHelloInputs(
                    serverName: self.configuration.serverName,
                    sessionID: Data(repeating: 0, count: 32),
                    x25519PublicKey: ephemeral.publicKey.rawRepresentation,
                    alpnProtocols: self.configuration.alpn,
                    random: random)
                var hello = try TLS13Fingerprint.chromeClientHello(inputs)
                let nonce = try AES.GCM.Nonce(data: random.suffix(12))
                let sealed = try AES.GCM.seal(clearSession, using: SymmetricKey(data: self.authKey),
                                              nonce: nonce, authenticating: hello)
                self.sessionID = sealed.ciphertext + sealed.tag
                guard self.sessionID.count == 32 else {
                    throw NativeOutboundError.crypto("REALITY 鉴权载荷长度异常")
                }
                hello.replaceSubrange(TLS13Fingerprint.sessionIDOffset..<(TLS13Fingerprint.sessionIDOffset + 32),
                                      with: self.sessionID)
                self.material = TLS13.ClientHelloMaterial(message: hello,
                                                          ephemeralPrivateKey: ephemeral)
                let record = try TLS13.plaintextRecord(contentType: .handshake,
                                                       legacyVersion: TLS13.legacyRecordVersionInitial,
                                                       fragment: hello)
                self.raw.send(record) { error in self.queue.async {
                    if let error { self.fail(error) } else { self.readRaw() }
                }}
                self.queue.asyncAfter(deadline: .now() + 12) { [weak self] in
                    guard let self, self.phase == .handshaking else { return }
                    self.fail(NativeOutboundError.connection("REALITY TLS 握手超时"))
                }
            } catch { self.fail(error) }
        }
    }

    func send(_ data: Data, completion: @escaping (Error?) -> Void) {
        queue.async {
            guard self.phase == .ready else {
                completion(NativeOutboundError.connection("REALITY TLS 尚未就绪")); return
            }
            self.sendQueue.append((data, completion)); self.flushSendQueue()
        }
    }

    func receive(completion: @escaping (Data?, Bool, Error?) -> Void) {
        queue.async {
            guard self.phase != .closed else { completion(nil, true, nil); return }
            guard self.receiveCompletion == nil else {
                completion(nil, true, NativeOutboundError.protocolError("REALITY TLS 不支持并发 receive")); return
            }
            if self.visionDirectRead, !self.directReadBuffer.isEmpty {
                let value = self.directReadBuffer
                self.directReadBuffer.removeAll(keepingCapacity: true)
                completion(value, false, nil)
            } else if self.plaintextHead < self.plaintextQueue.count {
                let data = self.plaintextQueue[self.plaintextHead]; self.plaintextHead += 1
                self.compactPlaintextQueue(); completion(data, false, nil)
            } else {
                self.receiveCompletion = completion; self.readRaw()
            }
        }
    }

    func enableVisionDirectWrite() {
        onQueueSync { self.visionDirectWrite = true }
    }

    func enableVisionDirectRead() {
        onQueueSync {
            guard !self.visionDirectRead else { return }
            self.visionDirectRead = true
            self.directReadBuffer.append(self.recordReader.takePendingBytes())
        }
    }

    private func onQueueSync(_ body: () -> Void) {
        if DispatchQueue.getSpecific(key: queueKey) != nil { body() }
        else { queue.sync(execute: body) }
    }

    func cancel() { queue.async { self.close(nil) } }

    private func readRaw() {
        guard phase != .closed, !receivingRaw else { return }
        if !visionDirectRead, recordReader.pendingByteCount > 0 {
            do { try consume(Data()) } catch { fail(error); return }
            if receiveCompletion == nil { return }
        }
        receivingRaw = true
        raw.receive { data, complete, error in self.queue.async {
            self.receivingRaw = false
            if let error { self.fail(error); return }
            if let data, !data.isEmpty {
                if self.visionDirectRead {
                    if let completion = self.receiveCompletion {
                        self.receiveCompletion = nil; completion(data, false, nil)
                    } else { self.directReadBuffer.append(data) }
                } else {
                    do { try self.consume(data) } catch { self.fail(error); return }
                }
            }
            if complete { self.close(nil); return }
            if self.phase == .handshaking || self.receiveCompletion != nil { self.readRaw() }
        }}
    }

    private func consume(_ data: Data) throws {
        recordReader.append(data)
        while let record = try recordReader.next() {
            switch phase {
            case .handshaking: try consumeHandshakeRecord(record)
            case .ready:
                if try consumeApplicationRecord(record) { return }
            case .closed: return
            }
        }
    }

    private func consumeHandshakeRecord(_ record: TLS13.Record) throws {
        if record.contentType == TLS13.ContentType.changeCipherSpec.rawValue { return }
        if transcript == nil {
            guard record.contentType == TLS13.ContentType.handshake.rawValue else {
                throw NativeOutboundError.protocolError("REALITY TLS 期待明文 ServerHello")
            }
            handshakeReader.append(record.fragment)
            guard let message = try handshakeReader.next(),
                  message.handshakeType == .serverHello,
                  let material else {
                throw NativeOutboundError.protocolError("REALITY TLS ServerHello 不完整或类型错误")
            }
            let hello = try TLS13.ServerHello(message.body)
            guard hello.legacySessionIDEcho == sessionID else {
                throw NativeOutboundError.protocolError("REALITY TLS ServerHello session_id echo 不匹配")
            }
            guard hello.keyShareGroup == 0x001d else {
                throw NativeOutboundError.protocolError("REALITY TLS 服务端未选择 X25519")
            }
            var transcript = TLS13.Transcript(hello.cipherSuite.hashFunction)
            transcript.update(material.message); transcript.update(message.raw)
            helloTranscriptHash = transcript.value
            var schedule = TLS13.KeySchedule(suite: hello.cipherSuite)
            try schedule.advance(sharedSecret: TLS13.x25519(
                privateKey: material.ephemeralPrivateKey, peerPublicKey: hello.keyShareData))
            let serverSecret = try schedule.trafficSecret(.serverHandshake,
                                                          transcriptHash: transcript.value)
            serverHandshakeProtector = try TLS13.RecordProtector(suite: hello.cipherSuite,
                                                                 trafficSecret: serverSecret)
            self.transcript = transcript; self.schedule = schedule
            return
        }
        guard let protector = serverHandshakeProtector else {
            throw NativeOutboundError.crypto("REALITY TLS 缺少服务端握手密钥")
        }
        guard record.contentType == TLS13.ContentType.applicationData.rawValue else {
            throw NativeOutboundError.protocolError("REALITY TLS 握手密文的外层类型错误")
        }
        let opened = try protector.unprotect(record)
        if opened.contentType == TLS13.ContentType.alert.rawValue {
            throw NativeOutboundError.protocolError(try TLS13.Alert(opened.content).text)
        }
        guard opened.contentType == TLS13.ContentType.handshake.rawValue else { return }
        handshakeReader.append(opened.content)
        while let message = try handshakeReader.next() { try consumeHandshakeMessage(message) }
    }

    private func consumeHandshakeMessage(_ message: TLS13.HandshakeMessage) throws {
        guard var transcript, let schedule else {
            throw NativeOutboundError.crypto("REALITY TLS transcript 未初始化")
        }
        switch message.handshakeType {
        case .encryptedExtensions:
            _ = try TLS13.EncryptedExtensions(message.body)
            transcript.update(message.raw)
        case .certificate:
            let certificates = try TLS13.CertificateMessage(message.body)
            guard let der = certificates.leaf else {
                throw NativeOutboundError.protocolError("REALITY TLS 缺少叶子证书")
            }
            let leaf = try TLS13.LeafCertificate(der: der)
            guard leaf.isEd25519, leaf.signatureAlgorithm == TLS13.LeafCertificate.ed25519OID else {
                throw NativeOutboundError.crypto("REALITY 未返回 Ed25519 伪造证书，可能已回落到真实站点")
            }
            let signature = Data(HMAC<SHA512>.authenticationCode(
                for: leaf.publicKey, using: SymmetricKey(data: authKey)))
            guard TLS13.constantTimeEquals(signature, leaf.signature) else {
                throw NativeOutboundError.crypto("REALITY 证书 HMAC 校验失败，可能是公钥/short-id 错误或遭到中间人")
            }
            self.leaf = leaf; transcript.update(message.raw)
        case .certificateVerify:
            guard let leaf else { throw NativeOutboundError.protocolError("CertificateVerify 早于 Certificate") }
            let verify = try TLS13.CertificateVerify(message.body)
            try TLS13.verifyCertificateVerify(algorithm: verify.algorithm,
                                               signature: verify.signature,
                                               publicKey: leaf.publicKey,
                                               transcriptHash: transcript.value)
            transcript.update(message.raw)
        case .finished:
            let serverSecret = try schedule.trafficSecret(.serverHandshake,
                                                          transcriptHash: helloTranscriptHash)
            let expected = try schedule.verifyData(secret: serverSecret,
                                                   transcriptHash: transcript.value)
            guard TLS13.constantTimeEquals(try TLS13.parseFinished(message.body,
                                                                   suite: schedule.suite), expected) else {
                throw NativeOutboundError.crypto("REALITY TLS 服务端 Finished 校验失败")
            }
            transcript.update(message.raw); self.transcript = transcript
            try finishClientHandshake()
            return
        default:
            throw NativeOutboundError.protocolError("REALITY TLS 收到意外的握手消息 \(message.type)")
        }
        self.transcript = transcript
    }

    private func finishClientHandshake() throws {
        guard let schedule, var transcript else { throw NativeOutboundError.crypto("REALITY TLS 握手状态缺失") }
        let serverFinishedHash = transcript.value
        let clientSecret = try schedule.trafficSecret(.clientHandshake,
                                                       transcriptHash: helloTranscriptHash)
        let verify = try schedule.verifyData(secret: clientSecret,
                                             transcriptHash: serverFinishedHash)
        var finished = Data([TLS13.HandshakeType.finished.rawValue, 0, 0,
                             UInt8(truncatingIfNeeded: verify.count)])
        finished.append(verify)
        let clientHandshakeProtector = try TLS13.RecordProtector(suite: schedule.suite,
                                                                 trafficSecret: clientSecret)
        let encryptedFinished = try clientHandshakeProtector.protect(contentType: .handshake,
                                                                      content: finished)
        clientApplicationSecret = try schedule.trafficSecret(.clientApplication,
                                                              transcriptHash: serverFinishedHash)
        serverApplicationSecret = try schedule.trafficSecret(.serverApplication,
                                                              transcriptHash: serverFinishedHash)
        clientApplicationProtector = try TLS13.RecordProtector(suite: schedule.suite,
                                                               trafficSecret: clientApplicationSecret!)
        serverApplicationProtector = try TLS13.RecordProtector(suite: schedule.suite,
                                                               trafficSecret: serverApplicationSecret!)
        transcript.update(finished); self.transcript = transcript
        raw.send(TLS13.changeCipherSpecRecord + encryptedFinished) { error in self.queue.async {
            if let error { self.fail(error); return }
            self.phase = .ready
            let completion = self.handshakeCompletion; self.handshakeCompletion = nil
            completion?(.success(self))
            if self.receiveCompletion != nil { self.readRaw() }
        }}
    }

    private func consumeApplicationRecord(_ record: TLS13.Record) throws -> Bool {
        if record.contentType == TLS13.ContentType.changeCipherSpec.rawValue { return false }
        guard let protector = serverApplicationProtector else {
            throw NativeOutboundError.crypto("REALITY TLS 缺少应用流量密钥")
        }
        let opened = try protector.unprotect(record)
        switch TLS13.ContentType(rawValue: opened.contentType) {
        case .applicationData:
            if !opened.content.isEmpty { deliver(opened.content); return true }
        case .alert:
            let alert = try TLS13.Alert(opened.content)
            if alert.isCloseNotify { close(nil) }
            else { throw NativeOutboundError.protocolError(alert.text) }
        case .handshake:
            handshakeReader.append(opened.content)
            while let message = try handshakeReader.next() {
                if message.handshakeType == .keyUpdate {
                    let request = try TLS13.KeyUpdateRequest(message.body)
                    try serverApplicationProtector?.updateKeys()
                    if request == .requested { try sendKeyUpdateResponse() }
                } else if message.handshakeType != .newSessionTicket {
                    throw NativeOutboundError.protocolError("REALITY TLS 收到未支持的后握手消息 \(message.type)")
                }
            }
        default: break
        }
        return false
    }

    private func sendKeyUpdateResponse() throws {
        guard let protector = clientApplicationProtector else { return }
        let message = Data([TLS13.HandshakeType.keyUpdate.rawValue, 0, 0, 1, 0])
        let record = try protector.protect(contentType: .handshake, content: message)
        try protector.updateKeys()
        raw.send(record) { error in if let error { self.queue.async { self.fail(error) } } }
    }

    private func flushSendQueue() {
        guard !sending, phase == .ready, !sendQueue.isEmpty else { return }
        sending = true
        let (data, completion) = sendQueue.removeFirst()
        if visionDirectWrite {
            raw.send(data) { error in self.queue.async {
                self.sending = false; completion(error)
                if let error { self.fail(error) } else { self.flushSendQueue() }
            }}
            return
        }
        do {
            guard let protector = clientApplicationProtector else {
                throw NativeOutboundError.crypto("REALITY TLS 缺少应用写密钥")
            }
            var records = Data(); var offset = 0
            while offset < data.count {
                let end = min(data.count, offset + TLS13.maximumPlaintextLength)
                records.append(try protector.protect(contentType: .applicationData,
                                                      content: Data(data[offset..<end])))
                offset = end
            }
            raw.send(records) { error in self.queue.async {
                self.sending = false; completion(error)
                if let error { self.fail(error) } else { self.flushSendQueue() }
            }}
        } catch { sending = false; completion(error); fail(error) }
    }

    private func deliver(_ data: Data) {
        if let completion = receiveCompletion {
            receiveCompletion = nil; completion(data, false, nil)
        } else { plaintextQueue.append(data) }
    }

    private func compactPlaintextQueue() {
        if plaintextHead == plaintextQueue.count { plaintextQueue.removeAll(keepingCapacity: true); plaintextHead = 0 }
    }

    private func fail(_ error: Error) { close(error) }

    private func close(_ error: Error?) {
        guard phase != .closed else { return }
        phase = .closed; raw.cancel()
        let handshake = handshakeCompletion; handshakeCompletion = nil
        handshake?(.failure(error ?? NativeOutboundError.connection("REALITY TLS 连接已关闭")))
        let receive = receiveCompletion; receiveCompletion = nil
        receive?(nil, true, error)
        let sends = sendQueue; sendQueue.removeAll()
        sends.forEach { $0.1(error ?? NativeOutboundError.connection("REALITY TLS 连接已关闭")) }
    }
}

public enum RealityTLSSelfTest {
    public static func run() throws {
        let publicKey = Data((0..<32).map(UInt8.init)).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
        let policy = ProxyPolicy(name: "reality-test", kind: .native,
                                 host: "127.0.0.1", port: 443, adapterType: "vless",
                                 parameters: [
                                    "uuid": "00000000-0000-0000-0000-000000000001",
                                    "security": "reality", "reality-public-key": publicKey,
                                    "reality-short-id": "0123456789abcdef",
                                    "client-fingerprint": "chrome"
                                 ])
        let configuration = try RealityTLSByteTransport.Configuration(
            policy: policy, fallbackServerName: "127.0.0.1")
        guard configuration.publicKey.count == 32,
              configuration.shortID == Data([0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef]),
              configuration.serverName == "127.0.0.1" else {
            throw NativeOutboundError.protocolError("REALITY 配置自测失败")
        }
        var malformed = policy
        malformed.parameters["reality-short-id"] = "xyz"
        guard (try? RealityTLSByteTransport.Configuration(
            policy: malformed, fallbackServerName: "127.0.0.1")) == nil else {
            throw NativeOutboundError.protocolError("REALITY 未拒绝无效 short-id")
        }
        let link = "vless://00000000-0000-0000-0000-000000000001@example.com:443" +
            "?security=reality&sni=cdn.example.com&fp=chrome&pbk=\(publicKey)" +
            "&sid=0123456789abcdef#reality"
        let imported = try ShareLinkSubscription.parse(link)
        guard let node = imported.proxies.first,
              node.parameters["security"] == "reality",
              node.parameters["reality-public-key"] == publicKey,
              node.parameters["reality-short-id"] == "0123456789abcdef" else {
            throw NativeOutboundError.protocolError("REALITY 分享链接导入自测失败")
        }
    }
}
